# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: build

on:
  push:
    tags:
      - '*.*.*'
  workflow_dispatch:


jobs:
  build:
    name: Publish webextension
    env:
      EXTENSION_DIR_PATH: './dist'
      PACKED_ZIP_PATH: 'extension.zip'

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [v19.6.0]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - uses: olegtarasov/get-tag@v2.1
      id: tagName

    - run: yarn install --frozen-lockfile
    - run: yarn build
    - run: yarn test


    - name: Pack directory
      id: packExtensionDir
      uses: cardinalby/webext-buildtools-pack-extension-dir-action@v1
      with:
          extensionDir: ${{ env.EXTENSION_DIR_PATH }}
          zipFilePath: ${{ env.PACKED_ZIP_PATH }}
          zipIgnore: '*.git*|/*node_modules/*|*.eslint*'

    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
          name: enchancer-for-chatGPT-${{ steps.tagName.outputs.tag }}
          path: ${{ env.PACKED_ZIP_PATH }}